esphome:
  name: office-sensor
  platform: esp8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

i2c:

bme680_bsec:
  address: 0x77
  temperature_offset: 1

uart:
  rx_pin: D4
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Office Particulate Matter 2.5µm Concentration"
  - platform: bme680_bsec
    temperature:
      # Temperature in °C
      name: "Office Temperature"
      sample_rate: lp
      filters:
        - median
    pressure:
      # Pressure in hPa
      name: "Office Pressure"
      sample_rate: lp
      filters:
        - median
    humidity:
      # Relative humidity %
      name: "Office Humidity"
      sample_rate: lp
      filters:
        - median
    gas_resistance:
      # Gas resistance in Ω
      name: "Office BME680 Gas Resistance"
      filters:
        - median
    iaq:
      # Indoor air quality value
      name: "Office IAQ"
      filters:
        - median
    iaq_accuracy:
      # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: "Office Numeric IAQ Accuracy"
    co2_equivalent:
      # CO2 equivalent estimate in ppm
      name: "Office CO2 Equivalent"
      filters:
        - median
    breath_voc_equivalent:
      # Volatile organic compounds equivalent estimate in ppm
      name: "Office Breath VOC Equivalent"
      filters:
        - median

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "Office IAQ Accuracy"
