esphome:
  name: office-occupancy-sensor
  platform: esp32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

binary_sensor:
  - platform: gpio
    pin: GPIO14
    name: "PIR Sensor"
    device_class: motion
